### ISSUE TITLE
PA review: User Interface

### ISSUE THREAD

**Issue by trevoruptain** [trevoruptain/TREVORNOTE#10]

**Comment by debsfong** [comment]
It's not super intuitive that the logout button is that little silhouette person. Maybe use a closing door or that arrow thing? http://fontawesome.io/icon/sign-out/

Aside from that, it looks good to me!  Changing the icon isn't super high priority so I'm gonna go ahead and close this.

**Comment by trevoruptain** [comment]
Thanks for the feedback! I plan on having the silhouette trigger a dialogue
box that gives user info and a logout button.

Trevor
