### ISSUE TITLE
PA Review: Notes

### ISSUE THREAD

**Issue by trevoruptain** [trevoruptain/TREVORNOTE#11]

**Comment by debsfong** [comment]
This feature doesn't seem to be fully functional on Heroku. I can add a new note but it doesn't save. Sliding animations look cool! Comment when this has been fixed please!

**Comment by trevoruptain** [comment]
Okay, it's been fixed. A new user will have to create a notebook first, but at that point they can add notes. I plan on adding a default notebook and note for new users down the road.

**Comment by debsfong** [comment]
I'm having trouble figuring out how to add notes to a specific notebook, but I guess that's more part of the notebook MVP. 

One thing that need to be changed is that the textbox for the title should be bigger. I would suggest making it close to the entire width of the note.

**Comment by trevoruptain** [comment]
Done

**Comment by trevoruptain** [comment]
And yes, adding notebook ability will come with the Notebook MVP

**Comment by debsfong** [comment]
LGTM!
